### PR TITLE
skip binary prefix detection

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
WHOA Thank you so much. Pretty cool that all this is setup.

conda-forge infrastructure is really cool.

**Comment by hmaarrfk** [comment]
I renabled uploading so hopefully when this gets merged it should upload!

**Comment by hmaarrfk** [comment]
@jjhelmus is this something that needs to be pushed back to conda-forge?

**Comment by hmaarrfk** [comment]
i mean, without a selector for `# [aarch64]`

**Comment by jjhelmus** [comment]
Yes this change should get added to the conda-forge recipe.

**Pull request merged**
